### ISSUE TITLE
Listing datasets shouldn't trigger requests to each one

### ISSUE THREAD

**Issue by ldodds** [openactive/openactive.rb#6]
@digitalWestie in your recent change to the method that lists the OpenActive datasets, you've included the checks that test for conformance of each dataset to the specs.

This means that simply listing the datasets now takes several minutes to complete as we issue a request to each one before returning the list.

Checking conformance shouldn't be done in this method. It should be a quick lookup to build the basic array of dataset information.

Can you refactor the additional code into the dashboard app?

**Comment by digitalWestie** [comment]
Yeah, I see exactly what you mean, it's doing several things at once --- it's also doing the requests to github for issues too. Will move into dashboard.
